ref: https://blog.csdn.net/dong_learning/article/details/117851046

In [6]:
import torch

t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9, 8],
    [7, 6]
], dtype=torch.float32)

In [7]:
print(t1)

tensor([[1., 2.],
        [3., 4.]])


In [8]:
print(t1[0])

tensor([1., 2.])


In [9]:
print(t1[0][0])

tensor(1.)


In [10]:
print(t2[0][0])

tensor(9.)


In [11]:
print(t1 + t2)

tensor([[10., 10.],
        [10., 10.]])


In [12]:
print(t1 + 2)

tensor([[3., 4.],
        [5., 6.]])


In [13]:
print(t1 - 2)

tensor([[-1.,  0.],
        [ 1.,  2.]])


In [14]:
print(t1 * 2)

tensor([[2., 4.],
        [6., 8.]])


In [15]:
print(t1 / 2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [16]:
print(t1.add(2))

tensor([[3., 4.],
        [5., 6.]])


In [17]:
print(t1.sub(2))

tensor([[-1.,  0.],
        [ 1.,  2.]])


In [18]:
print(t1.mul(2))

tensor([[2., 4.],
        [6., 8.]])


In [19]:
print(t1.div(2))

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [20]:
import numpy as np

np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [21]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape),
    dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

In [22]:
t1 = torch.tensor([
    [1, 1],
    [1, 1]
], dtype=torch.float32)

t2 = torch.tensor([2, 4], dtype=torch.float32)

In [23]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [24]:
t1.shape

torch.Size([2, 2])

In [25]:
t2.shape

torch.Size([2])

In [28]:
t3 = torch.tensor(np.broadcast_to(t2, t1.shape))
print(t3)

tensor([[2., 4.],
        [2., 4.]])


In [29]:
t1 + t3

tensor([[3., 5.],
        [3., 5.]])

In [30]:
torch.tensor([1, 2, 3]) < torch.tensor([3, 1, 2])

tensor([ True, False, False])